%% bicicleta.m
% Script principal para executar as funções Q1 a Q8 do trabalho Bicicleta TS, incluindo arquivo complementar Q6_TScomganhos.m
% Autora: Priscila Dias

clear; clc; close all;

disp('==============================')
disp('   TRABALHO - BICICLETA TS    ')
disp('==============================')

scripts = { ...
    'Q1', ...             
    'Q2', ...             
    'Q3', ...             
    'Q4', ...             
    'Q5', ...             
    'Q6', ...             
    'Q6_TScomganhos', ... 
    'Q7', ...             
    'Q8', ...             
};

descricoes = { ...
    '1: Modelo TS exato do sistema usando abordagem da não linearidade setorial.', ...
    '2: Controlador por realimentação completa de estados do tipo u = Kx.', ...
    '3: Projeto de controlador PDC com taxa de decaimento via LMI.', ...
    '4: Simulação dos controladores com trajetória referência mantendo equilíbrio vertical.', ...
    '5: Simulação com trajetória senoidal para x3d = K sin(ωt) e x4d = K cos(ωt). Análise de K e ω máximos.', ...
    '6: Projeto de observador de estados considerando premissas conhecidas.', ...
    '6b: Ganhos do observador para cada regra (complementar a Q6).', ...
    '7: Projeto de observador de estados considerando que apenas x1 e x3 são medidos.', ...
    '8: Simulação dos estimadores e comparação premissas conhecidas vs desconhecidas.'
};

n_scripts = length(scripts);

script_atual = '';  % Definido aqui para visibilidade no catch

for k = 1:n_scripts
    fprintf('\n========================================\n');
    fprintf('Executando Questão %d:\n%s\n\n', k, descricoes{k});
    
    script_atual = scripts{k};  % sempre antes do try
    
    fprintf('Executando script: %s\n', script_atual);
    
    try
        feval(script_atual);  % chama a função/script pelo nome
        fprintf('Questão %d concluída com sucesso.\n', k);
    catch ME
        warning('Erro ao executar %s:\n%s', script_atual, ME.message);
    end
    
    fprintf('Pressione qualquer tecla para continuar para a próxima questão...\n');
    pause;
end

fprintf('\n==============================\n');
fprintf('Execução completa de todas as questões Q1 a Q8 e arquivos complementares.\n');
fprintf('Verifique os gráficos e resultados no relatório.\n');
fprintf('==============================\n');
